version: '3.3'

services:
  caddy: 
    depends_on:
      - ghost
    container_name: ${CONTAINER_CADDY_NAME}
    image: lucaslorentz/caddy-docker-proxy:alpine
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
      - 2015:2015
    command: -quic -email ${LETSENCRYPT_EMAIL} -agree=true -log stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CADDY_PATH}:/root/.caddy
    
  ghost:
    depends_on:
      - db
    container_name: ${CONTAINER_GHOST_NAME}
    image: ghost:alpine
    restart: unless-stopped
    volumes:
      - ${GHOST_CONTENT}:/var/lib/ghost/content
    env_file:
      - ./storage.env
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      
      url: ${URL}
      database__client: mysql
      database__connection__host: ${MYSQL_URL}
      database__connection__port: 3306
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}

      mail__transport: SMTP
      mail__from: "'NO-REPLY' <${MAIL_USERNAME}>"
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__secureConnection: ${MAIL_IS_SECURE}
      mail__options__auth__user: ${MAIL_USERNAME}
      mail__options__auth__pass: ${MAIL_PASSWORD}
      
    logging:
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-200k}
    labels:
      caddy.address: ${DOMAINS}
      caddy.targetport: "2368"
      caddy.proxy.transparent: ""
      caddy.gzip: ""

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

networks:
    default:
       external:
         name: ${NETWORK}